package prog3;
import java.lang.Thread;
import java.util.*;
import java.util.Random;

public class Multithread
{
	public static void main(String args[])
    {
		first th=new first();
	    th.start();
	}
}

class first extends Thread
{
  public void run()
  {
    int n, t;
    Scanner sc=new Scanner(System.in);
    Random r=new Random();
    try
    {
    	System.out.println("Enter number of random values to be generated ");
    	n=sc.nextInt();
        for(int i=0;i<n;i++)
        {
           t=r.nextInt(100);
           System.out.println("\nThe number generated by First thread -> "+t);
           Thread t2=new second(t);
           t2.start();
           Thread t3=new third(t);
           t3.start();
           Thread.sleep(1000);
        }
    } 
     catch(InterruptedException e)
     {
        System.out.println(e);
     }
   }
}

class second extends Thread
{
  public double square;
  public int j;
  public second (int num1)
  {
   j=num1;
   square=Math.pow(j,2);
  }
  public void run()
  {
    System.out.println("Second thread -> SQUARE => "+square);
  }
}

class third extends Thread
{
  public double cube;
  public int k;
  public third(int num2)
  {
    k=num2;
    cube=Math.pow(k,3);
  }
  public void run()
  {
    System.out.println("Third thread -> CUBE => "+cube );
  }
}
